### ISSUE TITLE
idea: move non-working iOS stuff into branch

### ISSUE THREAD

**Issue by aginiewicz** [ajhager/libgdx-sbt-project.g8#39]
I'd say that it would be good to move all iOS stuff into separate branch, before it is ready for release - and afaik it does not work (there is one issue about it) nor is plugged into any sbt project.

For people who wants to work on it, there is no problem, because g8 has support to pull a branch directly.

**Comment by ajhager** [comment]
I am definitely fine with this. I keep waiting on Mario to announce the new iOS support for libgdx (which would hopefully allow Scala support.)

There is not an iOS sbt project per se, but there _is_ support for extracting the iOS libraries and added support in the iOS project files for precompiling using sbt and including scala jars. Moving it into a separate branch makes sense for now.

**Comment by aginiewicz** [comment]
Yeah, I also hope this RoboVM backend will allow us to run Scala+LibGDX code on iOS.

Btw, I think I can do it, but I will wait with it for decision about sbt-android 0.7 update pull request, because rebasing on top of that change wouldn't be easy.

**Comment by ajhager** [comment]
Mario just announced the deprecation of the old iOS backend, which is no longer working even with Java targets, so I think the plan for this should be to remove the iOS stuff completely instead of starting a new branch for it. Once RoboVM is in the nightlies we can add in a clean implementation.

I'm testing the sbt-android 0.7 pull request right now.

**Comment by aginiewicz** [comment]
I've sent fresh pull request with this and one extra change.
