### ISSUE TITLE
Explore using properties files for some options so they can be tweaked later

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#48]

**Comment by aginiewicz** [comment]
Good functionality, from my point of view mostly because stuff like version number is used in several places around Build.scala - it could be Properties object which will be used in other places as well, might be easier to implement and give similar functionality.

**Comment by aginiewicz** [comment]
Seems this one is getting more and more important, and will solve quite some number of issues - or make them solvable at least.

I will try to look into it more soon, do you have any code sketch already for this in some local branch, or we are starting fresh?

Or maybe moving most of template to plugin first and using build.sbt will be easier?

**Comment by ajhager** [comment]
As you have pointed out, this change could really make the project better. This issue is my priority now. Let me know if you have any suggestions on how you would like to see it handled.

**Comment by aginiewicz** [comment]
I think that making it sbt keys would be nice, I think that build.sbt could be then quite similar to our current default.properties - and people could use same place to define config for other plugins as well. I think that this will be best in the long run.

But making this I think will require separating at least some part of this project into plugin, so we can add sbt plugin in build.sbt and configure there and be done. This will be done a lot easier in sbt 0.13, which is again better in long run.

Again going for new sbt requires us to switch to pfn plugin currently. I'm really worried about how stale the development of jberkel plugin become, just after nearly full rewrite it stopped. And it seems it got quite big task to maintain it. In contrast pfn plugin is smaller and while it does not have some useful features yet (like NDK integration), it grows quickly.

But to switch we need to change whole project layout into gradle project layout, with assets under android not under common - it is strange because they are shared, but unfortunately required.

This task almost sounds like starting the work on libgdx-sbt-project.g8 from scratch :/

We would probably need to start at the end - creating libgdx project using its gradle template, removing gradle build and replacing it with sbt-0.13 based pfn plugin. If we get it working, we should start making tamplate out of this. Then, we should start wrapping stuff up into plugin, and finally make it configurable using build.sbt.

I think that will be easiest way to handle it - and it will close us 50% of tickets :)

**Comment by aginiewicz** [comment]
I think that this is fixed by #86, any other properties can be set the same way - trough custom SBT setting keys. It works quite well in my project (tested it on Specgine) and will also simplify potential future move to libgdx-sbt plugin.
