### ISSUE TITLE
Try out 2.11.0-m5 with the template.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#49]
Scala 2.11 has many improvements, but the most salient for the mobile use is the splitting up of the standard library. Proguard takes care of most of the bulk, but if nothing else it should speed up processing time on Android and iOS.

**Comment by aginiewicz** [comment]
The good news is that Typesafe decided to keep Java 6 minimum requirement for 2.11 ( http://grokbase.com/p/gg/scala-on-android/1385jp3ex5/android-and-scala-2-11-0 ) so everything should go smoothly with it.

Checking this now, with -m7 might be good idea, because -m8 (coming in two weeks) has no new features allowed.

**Comment by ajhager** [comment]
2.11.0-M7 seems to work well.
