### ISSUE TITLE
Test all IDE plugins to make sure they are still working with the template.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#54]

**Comment by photex** [comment]
The official Jetbrains SBT plugin (currently in nightlies) does't accept this project due to the handling of common/assets. I'd rather see the issue fixed in the plugin than with this template. I just thought it would be worth mentioning here.

**Comment by ajhager** [comment]
I will look into this anyway. It is very possible that the nightlies sbt plugin uses 0.13. sbt-andoid really needs to be upgraded soon so we can upgrade the rest of the project to 0.13 as well.

**Comment by aginiewicz** [comment]
@photex - can you check if it is still an issue with current template (that uses SBT 0.13 and files layout similar to gdx-setup.jar template generator?)

**Comment by tommyettinger** [comment]
Yes, it is still an issue.  I fixed it by manually changing project files.  I also needed to generate with:
`sbt "project core" gen-idea`
`sbt "project desktop" gen-idea`
`sbt "project android" gen-idea`
because `sbt "project common" gen-idea` couldn't find common.

**Comment by aginiewicz** [comment]
@tommyettinger 

this "common" was leftover from few versions back. It is of course "core" for core and so on.

Can you share what modifications you had to make to project files?

**Comment by tommyettinger** [comment]
Honestly, I'm unlikely to be able to reproduce them since I was really working by trial-and-error at first.  I remember the assets folder in the android project needed to be set up so desktop could see it, and ProGuard on Desktop needed to be configured to not remove enums needed for TextureAtlases to parse correctly.  I also needed to fiddle with run configurations a fair bit.  You can open my project from my github repo at https://github.com/tommyettinger/CommandersUnite/tree/master/commanders-unite , but I don't commit .idea/workspace.xml because it bloats Git changes.  My project can definitely build for desktop and android, thank you all for making this so (relatively) easy!

**Comment by ajhager** [comment]
It is untenable for me to keep up with every editor. For now we just support command line sbt workflow.
