### ISSUE TITLE
Texture packer convenience task

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#60]

**Comment by aginiewicz** [comment]
That would be great. I think

```
./common/assets_src/<directory=name_extension>/<images=list>
```

 would be good candidate for storing images that are going to be packed, then we could list all directories inside assets_src, and for each directory <D_ext> issue:

```
java -cp gdx.jar;extensions/gdx-tools/gdx-tools.jar com.badlogic.gdx.tools.imagepacker.TexturePacker2 <assets_src/D_ext> <assets> <D.png>
```

what do you think? I guess then we don't have to worry about giving this command parameters, it would be able to find all information itself from directory structure and files inside.

(separating assets and assets_src is I think easiest way to avoid filtering of assets during assembly of application)

**Comment by ajhager** [comment]
I created this https://github.com/ajhager/sbt-texturepacker a couple of months ago, but I think I like your idea better.

**Comment by magicgoose** [comment]
Good idea. But I have another question: is there an easy way to add another desktop project (or another run task with different Main class in existing desktop project) without learning sbt the hard way?
I'm currently migrating one game to Scala, and there we already have a custom piece of code to prepare game resources for different platforms. So I'm looking for easiest way to reuse it.

I tried searching the `build.scala` file for something similar to `desktop/run` (because this is the command that launches desktop project), but no luck.

**Comment by magicgoose** [comment]
@ajhager 
Alternatively, is there a way to pass command-line arguments to `desktop` project?
