### ISSUE TITLE
Test and Fix issues with Android API 19

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#63]

**Comment by aginiewicz** [comment]
Seems to be confirmed that I'm not only one with this issue: https://github.com/jberkel/android-plugin/issues/197

**Comment by aginiewicz** [comment]
I've reported issue upstream, to google: https://code.google.com/p/android/issues/detail?id=62583 because I don't know if this is same as https://code.google.com/p/android/issues/detail?id=61710 or new one, but seems not only Scala world is having issues with Build Tools 19 (even though platform image for Android API 19 itself works nicely with older build tools).

**Comment by aginiewicz** [comment]
Seems that with 19.0.1 it works, could you verify if it solved this issue globally (i.e. in at least one more case :))?

**Comment by ajhager** [comment]
This seems to be working just fine now.
