### ISSUE TITLE
Adding Ashley dependance to template

### ISSUE THREAD

**Issue by reyman** [ajhager/libgdx-sbt-project.g8#87]
Hi, 

Is it possible to add the ashley dependency easily to this scala g8 template ?
https://github.com/libgdx/ashley/wiki/Getting-started-with-Ashley 

Ashley seems to use gradle or maven, not sbt ...

Best regards,
SR

**Comment by aginiewicz** [comment]
I haven't tested it, but it should be enough to add

```
 "com.badlogicgames.ashley" % "ashley" % "1.1.0"
```

to list od libraryDependencies in build.scala below https://github.com/ajhager/libgdx-sbt-project.g8/blob/master/src/main/g8/project/build.scala#L21 after extra colon.

I don't think it is good idea to include it by default for all projects, because as I said it should be one-liner to include. Can you verify if it works for you?
